### ISSUE TITLE
UnicodeEncodeError on exception

### ISSUE THREAD

**Issue by seb-at-nzrs** [xmunoz/sodapy#20]
While uploading some data to Socrata with sodapy 1.2.0 and the upsert method, an Exception was raised due to status response, but the code failed as it seems the text coming from the server including UTF-8 characters.

Below is the traceback

```
  File "/Users/secastro/miniconda/lib/python2.7/site-packages/sodapy/__init__.py", line 221, in upsert
    return self._perform_update("post", resource, payload)
  File "/Users/secastro/miniconda/lib/python2.7/site-packages/sodapy/__init__.py", line 238, in _perform_update
    data=json.dumps(payload))
  File "/Users/secastro/miniconda/lib/python2.7/site-packages/sodapy/__init__.py", line 284, in _perform_request
    _raise_for_status(response)
  File "/Users/secastro/miniconda/lib/python2.7/site-packages/sodapy/__init__.py", line 332, in _raise_for_status
    http_error_msg += ".\n\t{0}".format(more_info)
UnicodeEncodeError: 'ascii' codec can't encode character u'\ufffd' in position 90: ordinal not in range(128)
```

I'm not uploading UTF-8 data, so I haven't tested specifically for that.

**Comment by xmunoz** [comment]
This seems odd to me, since the response is getting decoded from json before I do the string concatenation. When I tried to replicate locally, it would always trigger the exception 2 lines above on 
```
more_info = response.json().get("message")
```
Nonetheless, I did just push a small change that likely mitigates this problem. Can you test out this branch and see if it's still buggy?
https://github.com/xmunoz/sodapy/tree/uncode-error-20

**Comment by seb-at-nzrs** [comment]
I agree it's a very weird error, as the data gets properly encoded before being sent. I switched to a different language to do the data upload (Java) and that library also received a similar error, I'm leaning towards an error in Socrata's frontend. I'll follow up with their support. I'll test the patch.

**Comment by xmunoz** [comment]
I'm going to assume that this is no longer an issue, is it ok if I close it?

**Comment by chrismetcalf** [comment]
Actually, very relevant to this issue might be [the documentation I just added on the `$$bom` SoQL flag](https://dev.socrata.com/docs/queries/bom.html).

You should instruct your parser to parse the entire payload as UTF-8, since it may choke if it assumes ASCII and then later comes across UTF-8 characters. Or, as an alternative, you could add the `$$bom=true` flag to your request to force the inclusion of a Byte Order Mark at the beginning of the payload so that your parser flips into UTF-8 mode.

**Comment by xmunoz** [comment]
Good to know, thanks for the tip!

**Comment by xmunoz** [comment]
So I wasn't ever able to replicate, but I added a test [here](https://github.com/xmunoz/sodapy/commit/cca9d459d93d96a0ef6c33842ee987636e57b830) to ensure that unicode is supported.
